<?php

namespace AppBundle\Repository;

/**
 * LecturesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LecturesRepository extends \Doctrine\ORM\EntityRepository
{
}
