<?php

namespace AppBundle\Repository;

/**
 * totoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class totoRepository extends \Doctrine\ORM\EntityRepository
{
}
