# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    daisy:
                        password: daisypass
                        roles: 'ROLE_USER'
                    baltazar:
                        password: dollars
                        roles: 'ROLE_ADMIN'
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            http_basic: ~

    role_hierarchy:
        ROLE_ADMIN:     ROLE_USER
    
    access_control:
        # require ROLE_ADMIN for /admin*
        #- { path: ^/hey, roles: ROLE_ADMIN }